server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
## 连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xg?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'lwp123'
  #  设置静态资源路径  可从外部直接访问
  resources:
    static-locations:  classpath:/html/,classpath:/static/
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
## 整合MyBatis  须在启动类加上@MapperScan注解(dao所在的包) 或者 在每个dao加上@Mapper注解
# mybatis.config= classpath:mybatis-config.xml
mybatis:
  mapperLocations: classpath:mappers/*/*.xml,classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.test.xg.mapper: debug



